### ISSUE TITLE
OpenAPI generator failing to generate schema

### ISSUE THREAD

**Issue by dukeraphaelng** [PlaceOS/build#18]
- OpenAPI annotated following https://github.com/PlaceOS/build/pull/16, however an empty schema is generated

**Comment by kimburgess** [comment]
From testing, the annotation is definitely been applied to that method, however this does not occur until the `finished` macro hook runs. This will require some further digging, but initial thoughts are the upstream OpenAPI lib is likely attempting some parsing prior to this taking place.
