### ISSUE TITLE
Ensure binaries are ELF

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/build#33]
**Describe the bug**

A run of `build` on macos resulted in mach-o binaries in s3.

**Expected behavior**

Prevent the upload of non-elf binaries by reading the binary's [magic byte header](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format#File_header)

**Comment by stakach** [comment]
should we just embrace multi-platform?
i.e. have the binaries mark themselves as `x86-macos`, `arm7-linux` etc

**Comment by caspiano** [comment]
I don't see any reason. 
Static binaries are supported only for Linux, and we run drivers exclusively in Linux environments (or compose environments)

**Comment by caspiano** [comment]
Potentially ARM for edge drivers - but I'd rather survey whether that's necessary before implementing support for it

**Comment by stakach** [comment]
lol was going to be my next question:

are we differentiating on architecture though?
as if we all get M1/2 macs next year then we'll be developing in arm linux

**Comment by stakach** [comment]
I think having architecture specified is probably worthwhile
